### ISSUE TITLE
UNRaid Issue

### ISSUE THREAD

**Issue by Gaz492** [binhex/arch-sabnzbdvpn#3]
Everytime sabnzbd starts the following error is logged and it wont download anything.
` [18/Jun/2017:23:59:30] ENGINE Error in HTTPServer.tick
Traceback (most recent call last):
  File "/opt/sabnzbd/cherrypy/wsgiserver/__init__.py", line 2024, in start
    self.tick()
  File "/opt/sabnzbd/cherrypy/wsgiserver/__init__.py", line 2091, in tick
    s, ssl_env = self.ssl_adapter.wrap(s)
  File "/opt/sabnzbd/cherrypy/wsgiserver/ssl_builtin.py", line 67, in wrap
    server_side=True)
  File "/usr/lib/python2.7/ssl.py", line 363, in wrap_socket
    _context=self)
  File "/usr/lib/python2.7/ssl.py", line 611, in __init__
    self.do_handshake()
  File "/usr/lib/python2.7/ssl.py", line 840, in do_handshake
    self._sslobj.do_handshake()
error: [Errno 0] Error`

**Comment by binhex** [comment]
known bug with sabnzbd, see here for workaround:- https://forums.lime-technology.com/topic/44108-support-binhex-general/#comment-433612
